import { createHash } from "node:crypto";
import type { GeneratedCanonicalQuestion } from "./types";

/**
 * =========================================================
 * INTERNAL HELPERS
 * =========================================================
 */

function sha256(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

function stableJson(value: unknown): string {
  return JSON.stringify(sortDeep(value));
}

function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(sortDeep);
  }

  if (value && typeof value === "object") {
    const input = value as Record<string, unknown>;
    const out: Record<string, unknown> = {};

    for (const key of Object.keys(input).sort()) {
      out[key] = sortDeep(input[key]);
    }

    return out;
  }

  return value;
}

function normalizeText(value: string | null | undefined): string {
  return (value ?? "").trim();
}

/**
 * =========================================================
 * CORE NORMALIZATION
 * =========================================================
 */

export function normalizeQuestionForHash(
  question: GeneratedCanonicalQuestion
): Record<string, unknown> {
  return {
    itemType: question.itemType,
    operator: question.operator ?? null,
    lhsA: typeof question.lhsA === "number" ? question.lhsA : null,
    lhsB: typeof question.lhsB === "number" ? question.lhsB : null,
    rhs: typeof question.rhs === "number" ? question.rhs : null,
    equation: normalizeText(question.equation),
    promptText: normalizeText(question.promptText),
    answerText: normalizeText(question.answerText),
    difficulty: question.difficulty,
    contentJson: question.contentJson ?? null,
  };
}

/**
 * This is the canonical content hash for persistence / dedupe.
 * It intentionally excludes:
 * - sequence
 * - generatorVersion
 * - generatorMeta
 * so equivalent content hashes the same even if generated by
 * different runs or saved at different positions.
 */
export function hashGeneratedQuestion(
  question: GeneratedCanonicalQuestion
): string {
  return sha256(stableJson(normalizeQuestionForHash(question)));
}

export function hashGeneratedQuestions(
  questions: GeneratedCanonicalQuestion[]
): string[] {
  return questions.map(hashGeneratedQuestion);
}

/**
 * Whole-set fingerprint useful for debug / snapshot comparisons.
 * Order-sensitive on purpose.
 */
export function hashGeneratedQuestionSet(
  questions: GeneratedCanonicalQuestion[]
): string {
  return sha256(
    stableJson(questions.map((question) => normalizeQuestionForHash(question)))
  );
}

/**
 * Order-insensitive fingerprint useful for checking whether two
 * generated sets contain the same items regardless of sequence.
 */
export function hashGeneratedQuestionBag(
  questions: GeneratedCanonicalQuestion[]
): string {
  const itemHashes = questions.map(hashGeneratedQuestion).sort();
  return sha256(stableJson(itemHashes));
}

/**
 * Convenience alias for DB save path compatibility.
 */
export function buildContentSha256(
  question: GeneratedCanonicalQuestion
): string {
  return hashGeneratedQuestion(question);
}