ALTER TYPE "CanonicalItemType" ADD VALUE IF NOT EXISTS 'OAK_MULTIPLE_CHOICE';
ALTER TYPE "CanonicalItemType" ADD VALUE IF NOT EXISTS 'OAK_MULTI_BLANK_CHOICE';
ALTER TYPE "CanonicalItemType" ADD VALUE IF NOT EXISTS 'OAK_SHORT_ANSWER';
ALTER TYPE "CanonicalItemType" ADD VALUE IF NOT EXISTS 'OAK_MATCH';
ALTER TYPE "CanonicalItemType" ADD VALUE IF NOT EXISTS 'OAK_ORDER';
